# Copyright 2023 ETH Zurich and University of Bologna.
# Solderpad Hardware License, Version 0.51, see LICENSE for details.
# SPDX-License-Identifier: SHL-0.51

# Authors:
# - Thomas Benz <tbenz@iis.ee.ethz.ch>

stages:
  - nonfree

init:
  stage: nonfree
  script: make idma_nonfree_init
  artifacts:
    paths: [ nonfree/.gitlab-ci.yml ]

subpipe:
  stage: nonfree
  needs: [ init ]
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^__deploy__/
      when: never
    - when: always
  trigger:
    include:
      - artifact: nonfree/.gitlab-ci.yml
        job: init
    strategy: depend
