# Docs for iDMA

site_name: iDMA
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.footer

markdown_extensions:
  - markdown_grid_tables:
  - toc:
      toc_depth: 3

repo_url: https://github.com/FondazioneChipsIT/iDMA.git
repo_name: FondazioneChipsIT/iDMA

nav:
- Home:
  - index.md
  - Getting Started: gs.md
- Targets:
  - tg/index.md
  - Simulation: tg/sim.md
  - Cluster Integration: tg/cluster_integration.md
- User Manual:
  - um/index.md
  - Architecture: um/arch.md
  - Top Earlgrey Architecture: um/opentitan_integration.md
  - Frontend: um/frontend.md
  - Midend: um/midend.md
  - Backend: um/backend.md
  - Software Stack: um/sw.md
