import mem_ctrl_reg_pkg::*;

// Packet sent to the PHY-side CMD FIFO (CDC source FIFO)
typedef struct packed {
  logic [1:0]  protocol;
  logic [2:0]  transaction_type;
  logic [3:0]  response_type;
  logic [9:0]  data_size;
  logic [31:0] external_address;
} phy_cmd_t;

// Packet sent to the AXI master-side CMD FIFO
typedef struct packed {
  logic        transaction_type; // R/W direction extracted from the generic transaction type field
  logic [9:0]  data_size;
  logic [31:0] internal_address;
} axi_cmd_t;


module reg2cmdfifos (
    input logic clk_i,
    input logic rst_ni,

    //--------------------------------------
    // Interface from registers
    //--------------------------------------
    input mem_ctrl_reg2hw_t reg2hw_i,

    // One-cycle pulse generated when SW writes transaction_valid.
    // Equivalent to iDMA's next_id.re, but here it acts as a write trigger
    // because transaction_valid is a normal RW register and not a prim_subreg_ext.
    input logic transaction_valid_pulse_i,

    //--------------------------------------
    // CMD FIFO towards PHY (CDC source FIFO)
    //--------------------------------------
    output phy_cmd_t phy_cmd_o,
    output logic     phy_cmd_valid_o,
    input  logic     phy_cmd_ready_i,
    input  logic     phy_full_i,

    //--------------------------------------
    // CMD FIFO towards AXI master
    //--------------------------------------
    output axi_cmd_t axi_cmd_o,
    output logic     axi_cmd_valid_o,
    input  logic     axi_cmd_ready_i,
    input  logic     axi_full_i,

    //--------------------------------------
    // Status towards reg_mem_ctrl / SW
    //--------------------------------------
    output logic push_error_o,  // Kept for compatibility/debug, currently always 0
    output logic sync_error_o,  // Kept for compatibility/debug, currently always 0

    // Indicates whether both FIFOs have available space.
    // reg_mem_ctrl uses this signal to decide whether to accept or block
    // the transaction_valid write (through APB PREADY).
    output logic space_available_o
);


  //--------------------------------------
  // FIFO availability and synchronization
  //--------------------------------------

  // Both FIFOs must accept the command at the same time.
  // The transaction_valid write is blocked upstream until both FIFOs have space,
  // therefore a valid command always finds space available in both FIFOs.
  assign space_available_o = phy_cmd_ready_i & axi_cmd_ready_i;


  // The two FIFOs are pushed together when transaction_valid is written.
  assign phy_cmd_valid_o = transaction_valid_pulse_i;
  assign axi_cmd_valid_o = transaction_valid_pulse_i;


  // Kept for compatibility/debug.
  // With upstream backpressure (and, since the fix in mem_ctrl_reg_wrap, an
  // atomic check-and-push pulse) this condition should never occur.
  // It is useful as an assertion/debug condition.
  assign push_error_o = transaction_valid_pulse_i & ~space_available_o;

`ifndef SYNTHESIS
  // Regression guard for the check-and-push atomicity invariant: a push
  // pulse must never be generated without space available in both FIFOs.
  // If this fires, the upstream backpressure/pulse-generation atomicity has
  // been broken (e.g. a future edit reintroduces a check/push timing skew,
  // or a second producer is added to these FIFOs).
  assert property (@(posedge clk_i) disable iff (!rst_ni)
    !push_error_o
  ) else $error("reg2cmdfifos: push attempted without space_available (transaction dropped)");
`endif


  // Detects a possible loss of synchronization between the two FIFOs.
  assign sync_error_o = phy_full_i ^ axi_full_i;


  //--------------------------------------
  // Packet construction
  //--------------------------------------

  // Register field access follows the hierarchy generated by reggen.
  //
  // Multi-field registers (e.g. conf) are accessed as:
  //   reg2hw_i.<register>.<field>.q
  //
  // Single-field registers are accessed as:
  //   reg2hw_i.<register>.q
  //
  // The hierarchy must match the generated mem_ctrl_reg_pkg.sv file.

  always_comb begin

    // Command packet sent to the PHY side.
    phy_cmd_o = '{
      protocol:         reg2hw_i.conf.protocol.q,
      transaction_type: reg2hw_i.conf.transaction_type.q,
      response_type:    reg2hw_i.conf.response_type.q,
      data_size:        reg2hw_i.data_size.q,
      external_address: reg2hw_i.external_address.q
    };


    // Command packet sent to the AXI master side.
    axi_cmd_o = '{
      // AXI requires only a 1-bit read/write direction.
      // The LSB of the generic transaction_type field is used as encoding.
      // The software-visible encoding must keep bit 0 as the R/W direction.
      transaction_type: reg2hw_i.conf.transaction_type.q[0],

      data_size:        reg2hw_i.data_size.q,
      internal_address: reg2hw_i.internal_address.q
    };

  end


endmodule