import mem_ctrl_reg_pkg::*;
import mem_ctrl_reg_bus_pkg::*;

module apb_top #(
    parameter int ADDR_WIDTH = 8,
    parameter int DATA_WIDTH = 32,
    parameter type reg_req_t = mem_ctrl_reg_req_t,
    parameter type reg_rsp_t = mem_ctrl_reg_rsp_t
) (
    input logic clk_i,
    input logic rst_ni,

    //--------------------------------------------------
    // APB Slave
    //--------------------------------------------------
    input  logic                  psel_i,
    input  logic                  penable_i,
    input  logic                  pwrite_i,
    input  logic [ADDR_WIDTH-1:0] paddr_i,
    input  logic [DATA_WIDTH-1:0] pwdata_i,

    output logic [DATA_WIDTH-1:0] prdata_o,
    output logic                  pready_o,
    output logic                  pslverr_o,

    //--------------------------------------------------
    // Hardware status interface (towards reg_mem_ctrl)
    //--------------------------------------------------
    input mem_ctrl_hw2reg_t hw2reg_i,

    //--------------------------------------------------
    // CMD FIFO towards PHY (CDC source FIFO)
    //--------------------------------------------------
    output phy_cmd_t phy_cmd_o,
    output logic     phy_cmd_push_o,
    input  logic     phy_full_i,

    //--------------------------------------------------
    // CMD FIFO towards AXI master
    //--------------------------------------------------
    output axi_cmd_t axi_cmd_o,
    output logic     axi_cmd_push_o,
    input  logic     axi_full_i
);

  //--------------------------------------------------
  // Internal interconnection signals
  //--------------------------------------------------

  // apb2reg <-> mem_ctrl_reg_wrap: a single req/rsp struct pair,
  // no more discrete signals for we/re/addr/wdata/rdata/ready.
  reg_req_t reg_req;
  reg_rsp_t reg_rsp;

  // mem_ctrl_reg_wrap <-> reg2cmdfifos
  mem_ctrl_reg2hw_t reg2hw;
  logic    transaction_valid_pulse;
  logic    space_available;
  logic    push_error;  // not connected externally, kept for internal debug
  logic    sync_error;  // not connected externally, kept for internal debug

  //--------------------------------------------------
  // apb2reg: converts APB into the reg_req_t/reg_rsp_t interface
  // (Feedthrough=1: default zero-wait-state behavior,
  //  actual wait states are generated by reg_rsp.ready downstream)
  //--------------------------------------------------
  apb2reg #(
      .Feedthrough(1'b1),
      .reg_req_t  (reg_req_t),
      .reg_rsp_t  (reg_rsp_t),
      .ADDR_WIDTH (ADDR_WIDTH),
      .DATA_WIDTH (DATA_WIDTH)
  ) i_apb2reg (
      .clk_i    (clk_i),
      .rst_ni   (rst_ni),

      .psel_i   (psel_i),
      .penable_i(penable_i),
      .pwrite_i (pwrite_i),
      .paddr_i  (paddr_i),
      .pwdata_i (pwdata_i),

      .prdata_o (prdata_o),
      .pready_o (pready_o),
      .pslverr_o(pslverr_o),

      .reg_req_o(reg_req),
      .reg_rsp_i(reg_rsp)
  );

  //--------------------------------------------------
  // mem_ctrl_reg_wrap: generated reg_top + backpressure on transaction_valid
  //--------------------------------------------------
  mem_ctrl_reg_wrap #(
      .ADDR_WIDTH(ADDR_WIDTH),
      .DATA_WIDTH( DATA_WIDTH),
      .reg_req_t (reg_req_t),
      .reg_rsp_t (reg_rsp_t)
  ) i_mem_ctrl_reg_wrap (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .reg_req_i(reg_req),
      .reg_rsp_o(reg_rsp),

      .reg2hw_o(reg2hw),
      .hw2reg_i(hw2reg_i),

      .transaction_valid_pulse_o(transaction_valid_pulse),
      .space_available_i        (space_available)
  );

  //--------------------------------------------------
  // reg2fifos: packs reg2hw data into the two Command FIFOs
  //--------------------------------------------------
  reg2fifos i_reg2fifos (
      .clk_i (clk_i),
      .rst_ni(rst_ni),

      .reg2hw_i(reg2hw),

      .transaction_valid_pulse_i(transaction_valid_pulse),

      .phy_cmd_o      (phy_cmd_o),
      .phy_cmd_push_o (phy_cmd_push_o),
      .phy_full_i     (phy_full_i),

      .axi_cmd_o      (axi_cmd_o),
      .axi_cmd_push_o (axi_cmd_push_o),
      .axi_full_i     (axi_full_i),

      .push_error_o     (push_error),
      .sync_error_o     (sync_error),
      .space_available_o(space_available)
  );

endmodule