// Defines reg_req_t/reg_rsp_t (REG_BUS interface) for the
// mem_ctrl block. Not generated by reggen: reggen only produces
// reg2hw_t/hw2reg_t (inside mem_ctrl_reg_pkg); the bus struct must be
// defined separately using the macro provided by register_interface.

`include "register_interface/typedef.svh"

package mem_ctrl_reg_bus_pkg;

  // Bus-side address width towards this block. It can be wider than
  // mem_ctrl_reg_pkg::BlockAw (5 bits, meaning up to 0x1F): the upper bits,
  // if present, are not used by the internal decoder of the generated
  // reg_top, which only looks at the lower BlockAw bits.
  localparam int unsigned AddrWidth = 8;
  localparam int unsigned DataWidth = 32;
  localparam int unsigned StrbWidth = DataWidth / 8;

  typedef logic [AddrWidth-1:0] mem_ctrl_reg_addr_t;
  typedef logic [DataWidth-1:0] mem_ctrl_reg_data_t;
  typedef logic [StrbWidth-1:0] mem_ctrl_reg_strb_t;

  `REG_BUS_TYPEDEF_ALL(mem_ctrl_reg, mem_ctrl_reg_addr_t, mem_ctrl_reg_data_t, mem_ctrl_reg_strb_t)

endpackage