import mem_ctrl_reg_pkg::*;
import mem_ctrl_reg_bus_pkg::*;
// NOTE: reg_req_t/reg_rsp_t come from mem_ctrl_reg_bus_pkg (defined with
// `REG_BUS_TYPEDEF_ALL, since reggen does not generate them: it only produces
// reg2hw_t/hw2reg_t, here with the mem_ctrl_ prefix). The import is
// defensive: the types are anyway passed as parameters (reg_req_t/reg_rsp_t)
// from apb_slave, but keeping it avoids ambiguity if in the future
// mem_ctrl_reg_req_t/_rsp_t are referenced by name inside this module.

module mem_ctrl_reg_wrap #(
    parameter int ADDR_WIDTH = 8,
    parameter int DATA_WIDTH = 32,
    parameter type reg_req_t  = logic,
    parameter type reg_rsp_t  = logic
) (
    input logic clk_i,
    input logic rst_ni,

    //--------------------------------------
    // REG_BUS interface, apb2reg side
    //--------------------------------------
    input  reg_req_t reg_req_i,
    output reg_rsp_t reg_rsp_o,

    //--------------------------------------
    // Hardware interface (unchanged towards the outside)
    //--------------------------------------
    output mem_ctrl_reg2hw_t reg2hw_o,
    input  mem_ctrl_hw2reg_t hw2reg_i,

    output logic transaction_valid_pulse_o,
    input  logic space_available_i
);

  // Offset generated by reggen (BlockAw = 5 bits, not ADDR_WIDTH):
  // mem_ctrl_reg_pkg::MEM_CTRL_TRANSACTION_VALID_OFFSET

  //--------------------------------------
  // Backpressure: decides whether to mask the 'valid' signal towards the
  // generated reg_top, and whether to keep the response 'ready' low.
  //--------------------------------------
  logic transaction_valid_write_attempt;
  assign transaction_valid_write_attempt =
      reg_req_i.valid & reg_req_i.write &
      (reg_req_i.addr[mem_ctrl_reg_pkg::BlockAw-1:0] ==
       mem_ctrl_reg_pkg::MEM_CTRL_TRANSACTION_VALID_OFFSET) &
      reg_req_i.wdata[0];

  logic block_write;
  assign block_write = transaction_valid_write_attempt & ~space_available_i;

  //--------------------------------------
  // Filtered request towards the generated reg_top: if block_write is high,
  // the 'valid' signal is not propagated, therefore the write is not
  // committed and the 'qe' of the transaction_valid field does not trigger.
  //--------------------------------------
  reg_req_t reg_req_filtered;
  reg_rsp_t reg_rsp_from_top;

  always_comb begin
    reg_req_filtered       = reg_req_i;
    reg_req_filtered.valid = reg_req_i.valid & ~block_write;
  end

  //--------------------------------------
  // Generated reg_top from reggen (name depends on the hjson: "mem_ctrl")
  //--------------------------------------
  mem_ctrl_reg_top #(
      .reg_req_t(reg_req_t),
      .reg_rsp_t(reg_rsp_t),
      .AW       (mem_ctrl_reg_pkg::BlockAw)
  ) i_mem_ctrl_reg_top (
      .clk_i    (clk_i),
      .rst_ni   (rst_ni),

      .reg_req_i(reg_req_filtered),
      .reg_rsp_o(reg_rsp_from_top),

      .reg2hw   (reg2hw_o),
      .hw2reg   (hw2reg_i),

      .devmode_i(1'b1)
  );

  //--------------------------------------
  // Response towards apb2reg: rdata/error come from the generated
  // reg_top, but the 'ready' signal is decided here because it is the
  // mechanism used to generate APB wait states when the FIFO is full.
  // apb2reg directly propagates this ready signal to pready_o.
  //--------------------------------------
  always_comb begin
    reg_rsp_o       = reg_rsp_from_top;
    reg_rsp_o.ready = ~block_write;
  end

  //--------------------------------------
  // Pulse towards reg2cmdfifos: generated combinationally in the SAME cycle
  // as the space_available_i check / PREADY decision (transaction_valid_
  // write_attempt & space_available_i, i.e. attempt & ~block_write).
  //
  // NOTE: previously this was assign transaction_valid_pulse_o =
  // reg2hw_o.transaction_valid.qe; qe is registered one cycle after 'we'
  // inside prim_subreg, which decouples the space_available_i check (cycle
  // N) from the actual FIFO push (cycle N+1). Under the current design this
  // does not lose commands only because (a) reg2cmdfifos is the sole
  // producer into phy_cmd/axi_cmd, and (b) a standards-compliant APB master
  // always inserts a SETUP cycle between two ACCESS phases, which happens
  // to absorb the one-cycle skew. Both are implicit environmental
  // assumptions, not structurally enforced. Driving the pulse directly from
  // the same-cycle combinational signal removes the skew entirely, so
  // check-and-push become atomic and correctness no longer depends on APB
  // transfer cadence or on reg2cmdfifos being the sole producer.
  //--------------------------------------
  assign transaction_valid_pulse_o = transaction_valid_write_attempt & space_available_i;

endmodule